### ISSUE TITLE
Feature: Custom responses for Chatbot

### ISSUE THREAD

**Issue by aryan31200** [IcHiGo-KuRoSaKiI/TelegramChatbotAIML#1]
### Is your feature request related to a problem? Please describe.

This chatbot has features already present in other chatbots

### Describe the solution you'd like

I would like to add my own set of responses for queries

**Comment by aryan31200** [comment]
Please assign this issue to me under hacktoberfest label

**Comment by IcHiGo-KuRoSaKiI** [comment]
Looking forward to your contributions!!
