### ISSUE TITLE
Feature:  Add file for fun facts

### ISSUE THREAD

**Issue by Himanshu-Agg12** [IcHiGo-KuRoSaKiI/TelegramChatbotAIML#4]
### Is your feature request related to a problem? Please describe.

This is a feature update for category of facts.

### Describe the solution you'd like

I want to add a file of funFacts.aiml according to category of humans,  animals etc.

### Additional context

Please assign this task to me under Hacktoberfest2021.

**Comment by IcHiGo-KuRoSaKiI** [comment]
Sure, will love to see the changes you'll make.
